In [3]:
import torch
import numpy as np

In [ ]:
np_zeros= np.zeros((2,2,2))
np_zeros


array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [16]:
print(np_zeros.dtype)

float64


In [8]:
np_arr = np.random.rand(3,4)
print(np_arr)
print(np.ndim(np_arr))
print(np.shape(np_arr))


[[0.18437291 0.31927826 0.95657538 0.4023085 ]
 [0.84122476 0.67526731 0.28724533 0.48052248]
 [0.60191977 0.34629158 0.37181967 0.34754453]]
2
(3, 4)


In [17]:
tensor_2d = torch.rand(3,4)
print(tensor_2d)
print(np.ndim(tensor_2d))
print(np.shape(tensor_2d))
print(tensor_2d.dtype)

tensor([[0.3142, 0.3349, 0.4908, 0.0288],
        [0.8227, 0.9697, 0.1226, 0.1664],
        [0.3325, 0.8281, 0.1136, 0.0333]])
2
torch.Size([3, 4])
torch.float32


In [22]:
torch1 = torch.arange(50)
print(torch1)
torch2 = torch1.reshape(5,-1)
print(torch2)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])


In [25]:
t1 = torch.arange(10)
t2 = t1.view(2,5)
print(t2)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


difference btw view and reshape

In [28]:
t2[1] = 444
print(t1)
print(t2)

tensor([  0,   1,   2,   3,   4, 444, 444, 444, 444, 444])
tensor([[  0,   1,   2,   3,   4],
        [444, 444, 444, 444, 444]])


In [32]:
torch2[2,3] = 5555
print(torch2)
print(torch1)
print(torch2.ndim)
print(torch2.shape)
print(torch1.ndim)
print(torch1.shape)

tensor([[   0,    1,    2,    3,    4,    5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
        [  20,   21,   22, 5555,   24,   25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
        [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49]])
tensor([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22, 5555,
          24,   25,   26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
          36,   37,   38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
          48,   49])
2
torch.Size([5, 10])
1
torch.Size([50])


In [33]:
torch2[:,4]

tensor([ 4, 14, 24, 34, 44])